packages:
    - 'packages/*'
    - 'apps/*'

catalog:
    '@primeuix/styled': ^0.4.1
    '@primeuix/utils': ^0.4.1
    '@primeuix/locale': ^0.0.1
    '@primeuix/styles': ^0.1.0-beta.2
    '@primeuix/themes': ^0.1.0-beta.4

catalogs:
    react19:
        "@types/react": "^19"
        "@types/react-dom": "^19"
        "react": "^19"
        "react-dom": "^19"
